version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper'
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - ./../persistent_data/zookeeper:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka'
    container_name: kafka
    depends_on:
      - zookeeper
    volumes:
      - ./../persistent_data/kafka:/bitnami/kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

  postgresqlBack:
    image: 'postgres'
    container_name: postgresqlBank
    ports:
      - '5432:5432'
    volumes:
      - ./../persistent_data/postgresqlBank:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank

  postgresqlKeycloak:
    image: 'postgres'
    container_name: postgresqlKeycloak
    ports:
      - '5433:5432'
    volumes:
      - ./../persistent_data/postgresqlKeycloak:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak

  mongodb:
    image: 'bitnami/mongodb'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./../persistent_data/mongodb:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=mongo
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=mongo
      - MONGODB_DATABASE=bank

  keycloak:
    image: 'bitnami/keycloak'
    container_name: keycloak
    depends_on:
      - postgresqlKeycloak
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgresqlKeycloak
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_DATABASE_NAME=keycloak


